---
# tasks file for McAfeeUninstall

- block:
    - name: Get the path of the MCafee installation
      win_stat: path="{{directory_remove_path}}"
      register: filestat

    - name: Remove McAfee Virusscan
      win_package:
          product_id: "{{prod_id}}"
          state: absent
      when: filestat.stat.exists == True
      register: virusscan_removal_info

    - debug: msg="{{virusscan_removal_info}}"
      tags:
        - virusscan_removed

    - name: Remove McAfee VirusAgent
      win_command: .\FrmInst.exe /forceuninstall
      args:
        chdir: "{{installation_directory}}"
      when: filestat.stat.exists == True
      register: agent_removal_info

    - debug: msg="{{agent_removal_info}}"
      tags:
        - virusagent_removed

    - name: Remove Registry Keys for Mcaffe
      win_regedit:
            path: "{{registry_path}}"
            state: absent
      tags:
        - registry_removed
      when: filestat.stat.exists == True

    - name: Remove MCaffe Folder from Program Files
      win_file:
         path: "{{directory_remove_path}}"
         state: absent
      when: filestat.stat.exists == True
      tags:
        - folder_removed
      
    
    - name: Reboot after MCaffe Uninstallation
      win_reboot:
      tags:
        - reboot
      when: filestat.stat.exists == True

  rescue:
   - debug: 
       msg: "The failed task was :  {{ ansible_failed_task.name }} for hostname  {{ hostvars[inventory_hostname]['inventory_hostname'] }}"
