---
- name: Adding  NIC's to VM
  vmware_guest:
      hostname: "{{hostname}}"
      datacenter: ha-datacenter
      username: "{{username}}"
      validate_certs: false
      password: "{{password}}"
      port: "{{port}}"
      name: "{{name}}"
      uuid: "{{uuid}}"
      state: poweredon 
      #operation: add
      networks:
      - name: 011_Infr_mgmt
        mac: 00:50:56:83:5d:43
        
        type: static
        ip: 10.202.192.55
        netmask: 255.255.255.0
        gateway: 10.202.192.1
        state: reconfigure
#        #device_type: e1000e
#        vlan: 11
        operation: edit
        start_connected: true
#      - name: 1201_hosted2_build1
#     nic:
#     - type: vmxnet3
#       network: 014_bur
#       operation: add
      
      wait_for_ip_address: yes 
  register: sonal
#      customization:
#        autologon: yes
#        hostname: "{{hostname}}"
#        username: "{{username}}"
#        validate_certs: false
#        password: "{{password}}"
#        port: "{{port}}"
#        name: "{{name}}"
#        uuid: "{{uuid}}"

#
#        networks: 
#        - name: "011_Infr_mgmt"
#          ip: "10.202.192.55"
#          netmask: "255.255.255.0"
#          gateway: "10.202.192.1"
#          state: connected
#        autologon: yes
#        device_type: e1000s
