--- 

- block:
    - name: Enabling UAC in Windows VM so as to uninstall softwares with admin access
      win_regedit:
       path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
       name: EnableLUA
       data: 1
       type: dword
  rescue:
   - debug: 
       msg: "The failed task was :  {{ ansible_failed_task.name }} for hostname  {{ hostvars[inventory_hostname]['inventory_hostname'] }}"
