---
#    - name: Find the disk present in Linux
    - shell: lsblk -o NAME,MODEL | awk '/Virtual disk/{print $1}' | awk 'END{print NR}'
      register: linux_vm_disk_facts
 
    - name: Compare the vmdks and drives present in VCenter and OS respectively
      debug: msg="The result of comparison for {{ hostvars[inventory_hostname]['inventory_hostname'] }} is TRUE with drives and vmdks as {{linux_vm_disk_facts.stdout}} and {{vcenter_disk_facts.guest_disk_facts["No_of_Disk_present"]}} respectively"

      when: vcenter_disk_facts.guest_disk_facts["No_of_Disk_present"] == linux_vm_disk_facts.stdout|int