---
- name: Adding  NIC's to VM
  vmware_portgroup:
      hostname: "{{hostname}}" 
      username: "{{username}}"
      validate_certs: false
      password: "{{password}}"
      port: "{{port}}"
      hosts: "{{name}}"      
     # uuid: "{{uuid}}"
      switch_name: "DVswitch01-A"
      portgroup_name: "011_Infr_mgmt"
      vlan_id: 11
  register: vnic_added
  tags:
    - added


