---
# VCenter details for Linux Machines

    - name: Gather disk information of the  required Linux vms
      sonam_custom_module_for_disk:
       hostname: "{{hostname}}"
       username: "{{username}}"
       password: "{{password}}"
       name: "{{ hostvars[item]['inventory_hostname'] }}"
       validate_certs: no
      with_items: '{{groups["linux"]}}'
      register: vcenter_disk_facts_of_linux



