   
- block:
   - name: Check whether the Service is present or not
     stat: path=/etc/init.d/ofxcontrollerd
     register: ofx_status

   - name: Kill the running process of OFX Controller
     command: pkill -9 ofxcontrolled
     when: ofx_status.stat.exists == True

   - name: Stop the OFX Controller service
     command: chkconfig ofxcontrollerd off
     when: ofx_status.stat.exists == True
 
   - name: Delete the OFX Controller Service from Chkconfig Management and remove any links in /etc/rc[0-6].d which pertain to it.
     command: chkconfig ofxcontrollerd --del
     when: ofx_status.stat.exists == True

   - name: Removing all the Files of Platespin
     file: path={{ item }} state=absent
     with_items:
      - /usr/lib/ofx
      - /etc/init.d/ofxcontrollerd
  #register: result

  rescue:
   - debug: 
       msg: "The failed task was :  {{ ansible_failed_task.name }} for hostname  {{ hostvars[inventory_hostname]['inventory_hostname'] }}"
   

